### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ductridev** [sunshine-tech/VietnamProvinces#1]
when I run : python -m dev -i dev/seed-data/Xa_2020-02-25.csv -o data/nested-divisions.json
it except error : UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 172: character maps to undefined
can you explain what i'm wrong ?

This is my installed package: 

Package                 Version
----------------------- ---------
absl-py                 0.9.0
appdirs                 1.4.4
astor                   0.8.1
attrs                   20.1.0
black                   19.10b0
click                   7.1.2
dlib                    19.17.0
face-recognition        1.2.3
face-recognition-models 0.3.0
fast-enum               1.3.0
first                   2.0.2
gast                    0.3.3
grpcio                  1.30.0
h5py                    2.10.0
idna                    2.6
importlib-metadata      1.6.1
imutils                 0.5.2
Keras                   2.2.4
Keras-Applications      1.0.8
Keras-Preprocessing     1.1.2
Logbook                 1.5.3
lxml                    4.5.1
Markdown                3.2.2
mock                    4.0.2
numpy                   1.16.2
opencv-contrib-python   4.0.0.21
pathspec                0.8.0
pip                     20.1.1
protobuf                3.12.2
pydantic                1.6.1
PyQt5                   5.15.0
PyQt5-sip               12.8.0
python-rapidjson        0.9.1
PyYAML                  5.3.1
rapidjson               1.0.0
regex                   2020.7.14
requests                2.18.4
scipy                   1.2.1
setuptools              41.2.0
single-version          1.2.2
tensorboard             1.13.1
tensorflow              1.13.1
tensorflow-estimator    1.13.0
termcolor               1.1.0
toml                    0.10.1
typed-ast               1.4.1
Unidecode               1.1.1
urllib3                 1.22
vietnam-provinces       0.2.1
Werkzeug                1.0.1
zipp                    3.1.0

**Comment by hongquan** [comment]
Why did you run `python -m dev`, instead of `python3 -m dev`? Are you sure your `python` is Python 3?

**Comment by hongquan** [comment]
No response from OP. Close now.

**Comment by TrisKnightGamer** [comment]
Yes, python3 in my pc is Python 3.6.7

**Comment by TrisKnightGamer** [comment]
#1
