### ISSUE TITLE
Pycharm gần như bị treo khi tiến trình index quá lâu

### ISSUE THREAD

**Issue by anhtran** [sunshine-tech/VietnamProvinces#6]
Mình không biết là cái này do lỗi Pycharm hay không? Nhưng mình chờ hơn 15 phút mà tiến trình index của Pycharm vẫn không kết thúc.

![Screen Shot 2021-12-21 at 4 53 23 PM](https://user-images.githubusercontent.com/115797/146909809-389f4ef2-631e-453e-bd18-14fb9ee83953.png)

**Comment by hongquan** [comment]
Hành động index là hành động riêng của PyCharm, không liên quan đến bản thân thư viện Python, nên mình không hỗ trợ được. Mình cũng không dùng PyCharm.
